language: go
matrix:
  include:
    - go: 1.4
      env: TOOLS_CMD=golang.org/x/tools/cmd
    - go: 1.3
      env: TOOLS_CMD=code.google.com/p/go.tools/cmd
    - go: 1.2
      env: TOOLS_CMD=code.google.com/p/go.tools/cmd

install:
 - export GOPATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH
 - export PATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH
 - go get ${TOOLS_CMD}/cover
 - go get ${TOOLS_CMD}/vet

script:
 - ./test

notifications:
  email: false
