language: go
matrix:
  include:
    - go: 1.4
      env: TOOLS_CMD=golang.org/x/tools/cmd
    - go: 1.3
      env: TOOLS_CMD=code.google.com/p/go.tools/cmd
    - go: 1.2
      env: TOOLS_CMD=code.google.com/p/go.tools/cmd

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

install:
 - go get ${TOOLS_CMD}/cover
 - go get ${TOOLS_CMD}/vet

script:
 - ./test

notifications:
  email: false
